export default [
  { slug: "ab-testing", name: "A/B testing" },
  { slug: "agile", name: "Agile" },
  { slug: "apollo-client", name: "Apollo Client" },
  { slug: "apollo-server", name: "Apollo Server" },
  { slug: "architecture", name: "Architecture" },
  { slug: "babel", name: "Babel" },
  { slug: "babel.js", name: "Babel (js)" },
  { slug: "bcrypt", name: "bcrypt" },
  { slug: "bookkeeping", name: "Bookkeeping" },
  { slug: "cdn", name: "CDN" },
  { slug: "ci-cd", name: "CI/CD" },
  { slug: "circleci", name: "CircleCI" },
  { slug: "classification", name: "Classification" },
  { slug: "cqrs", name: "CQRS" },
  { slug: "css", name: "CSS" },
  { slug: "css-in-js", name: "CSS-in-JS" },
  { slug: "css-grid", name: "CSS Grid" },
  { slug: "data", name: "Data" },
  { slug: "django", name: "Django", logo: "svg/django.svg" },
  { slug: "django-admin", name: "Django Admin" },
  { slug: "django-rest-framework", name: "Django REST" },
  { slug: "docker", name: "Docker" },
  { slug: "drupal", name: "Drupal" },
  { slug: "elastic", name: "Elastic" },
  { slug: "event-sourcing", name: "Event sourcing" },
  { slug: "express", name: "Express" },
  { slug: "fintech", name: "FinTech" },
  { slug: "flask", name: "Flask" },
  { slug: "freelance", name: "Freelance" },
  { slug: "gatsby", name: "Gatsby" },
  { slug: "gdpr", name: "GDPR" },
  { slug: "git", name: "git" },
  { slug: "gitlab", name: "Gitlab" },
  { slug: "google-analytics", name: "Google Analytics" },
  { slug: "google-cloud", name: "Google Cloud" },
  { slug: "google-cloud-build", name: "GCloud Build" },
  { slug: "google-optimize", name: "Google Optimize" },
  { slug: "government", name: "Government" },
  { slug: "graphene", name: "Graphene" },
  { slug: "graphql", name: "GraphQL" },
  { slug: "green-field", name: "Green-field" },
  { slug: "grpc", name: "gRPC" },
  { slug: "haproxy", name: "HAProxy" },
  { slug: "hardened", name: "Hardened" },
  { slug: "headless", name: "Headless" },
  {
    slug: "i18n",
    name: "i18n",
    description: `i18n is a numeronym of "Internationalization". It's the process of designing a software application so that it can be adapted to various languages and regions without engineering changes.`,
  },
  { slug: "image-processing", name: "Image processing" },
  { slug: "jenkins", name: "jenkins" },
  { slug: "jest", name: "Jest" },
  { slug: "jinja", name: "Jinja" },
  { slug: "jquery", name: "jQuery" },
  { slug: "jwt", name: "JWT", description: "JSON web token" },
  { slug: "kafka", name: "Kafka" },
  { slug: "kibana", name: "Kibana" },
  {
    slug: "l10n",
    name: "l10n",
    description: `l10n is a numeronym of "Localization". It's the process of adapting internationalized software for a specific region or language by translating text and adding locale-specific components.`,
  },
  { slug: "linux", name: "Linux" },
  { slug: "loader.io", name: "loader.io" },
  { slug: "logstash", name: "Logstash" },
  { slug: "machine-learning", name: "Machine learning" },
  { slug: "macos", name: "MacOS" },
  { slug: "media", name: "Media" },
  { slug: "memcached", name: "memcached" },
  { slug: "microservices", name: "Microservices" },
  { slug: "monorepo", name: "Monorepo" },
  { slug: "neural-network", name: "Neural network" },
  { slug: "next.js", name: "Next.js" },
  { slug: "nginx", name: "Nginx" },
  { slug: "nosql", name: "NoSQL" },
  { slug: "oauth", name: "OAuth" },
  { slug: "opencv", name: "OpenCV" },
  { slug: "open-source", name: "Open Source" },
  { slug: "performance", name: "Performance" },
  { slug: "performance-management", name: "Performance management" },
  { slug: "pm2", name: "pm2" },
  { slug: "postgres", name: "PostgreSQL" },
  { slug: "product-owner", name: "Product owner" },
  { slug: "protobuf", name: "Protobuf" },
  { slug: "publishing", name: "Publishing" },
  { slug: "puppeteer", name: "Puppeteer" },
  { slug: "rabbitmq", name: "RabbitMQ" },
  {
    slug: "react",
    name: "React",
    description: `
			React is a JavaScript library for building user interfaces.
			It's declarative, reactive and component based. I've used React on several
			projects and became my go-to library for building user interfaces.
		`,
  },
  { slug: "realtime", name: "Realtime" },
  { slug: "redis", name: "Redis" },
  { slug: "relay", name: "Relay" },
  { slug: "responsive", name: "Responsive" },
  { slug: "rest", name: "RESTful" },
  {
    slug: "rollup",
    name: "Rollup.js",
    description: `
			Rollup is a module bundler for JavaScript which compiles small pieces
			of code into something larger and more complex, such as a library or
			application. 
		`,
  },
  { slug: "sapper", name: "Sapper" },
  { slug: "scrum", name: "Scrum" },
  { slug: "scrum-master", name: "Scrum master" },
  { slug: "security", name: "Security" },
  { slug: "seo", name: "SEO" },
  { slug: "serverless", name: "Serverless" },
  { slug: "siege", name: "Siege" },
  {
    slug: "spa",
    name: "SPA",
    description: `
			A single-page application (SPA) is a web application or web site that
			interacts with the user by dynamically rewriting the current page rather
			than loading entire new pages from a server. I've been building SPA's
			since 2012.
		`,
  },
  { slug: "speed", name: "Speed" },
  { slug: "sqlalchemy", name: "SQLAlchemy" },
  { slug: "ssr", name: "SSR" },
  { slug: "startup", name: "Startup" },
  { slug: "static-site", name: "Static site" },
  { slug: "streams", name: "Streams" },
  { slug: "styled-components", name: "Styled-components" },
  { slug: "subscriptions", name: "Subscriptions" },
  {
    slug: "svelte",
    name: "Svelte",
    description: "Svelte is a javascript library ...",
  },
  { slug: "tag-manager", name: "Tag Manager" },
  { slug: "tensorflow", name: "Tensorflow" },
  { slug: "tensorflow.js", name: "Tensorflow.js" },
  { slug: "thumbor", name: "Thumbor" },
  { slug: "transactional-email", name: "Transactional email" },
  { slug: "tuintuin", name: "TuinTuin" },
  { slug: "typographyjs", name: "Typography.js" },
  { slug: "universal", name: "Universal" },
  { slug: "uwsgi", name: "uWSGI" },
  { slug: "varnish", name: "Varnish" },
  { slug: "wbso", name: "WBSO" },
  { slug: "webdriver", name: "Webdriver" },
  { slug: "webpack", name: "Webpack" },
];
