name: imgproxy

on:
  push:
    branches: 
      - master

jobs:
  lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: zip lambda.zip apps/imgproxy
      - uses: stcalica/update-lambda
        with:
          package: lambda.zip
          function-name: imgproxy
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
